### ISSUE TITLE
Dengue Stop Milestones for GSoC 2020

### ISSUE THREAD

**Issue by DonOmalVindula** [scorelab/dengue-stop#309]
Please find the detailed project plan [here.](https://docs.google.com/document/d/1Yhu3SrcbS6-3lBwCDFJQ2sGnQfRRdk_eN8BZ1VZ5vXM/edit?usp=sharing)
<details><summary>Proposed UI Mockups</summary>

### Login Screen (Mobile)

<kbd>![Login](https://user-images.githubusercontent.com/42619922/82601026-7feb9280-9bcc-11ea-9fca-42c8b6803d40.png)</kbd>

### Signup Screen (Mobile)

<kbd>![Register](https://user-images.githubusercontent.com/42619922/82601629-7adb1300-9bcd-11ea-963c-da8b47ae2bb9.png)</kbd>

### Home Screen (Mobile)

<kbd>![Home](https://user-images.githubusercontent.com/42619922/82601652-83cbe480-9bcd-11ea-8fd8-8ce1043487c1.png)</kbd>

### New Incident Screen (Mobile)

<kbd>![Report Incident](https://user-images.githubusercontent.com/42619922/82601684-947c5a80-9bcd-11ea-9197-6bc7e781467b.png)</kbd>

### My Reports Screen (Mobile)

<kbd>![My Reports](https://user-images.githubusercontent.com/42619922/82601713-a3630d00-9bcd-11ea-9c41-3074cd55a472.png)</kbd>

### My Profile Screen (Mobile)

<kbd>![My Profile](https://user-images.githubusercontent.com/42619922/82601747-acec7500-9bcd-11ea-8bd1-a60c43916a41.png)</kbd>

----

### Login Screen (Web)

<kbd>![Login_wo_logo](https://user-images.githubusercontent.com/42619922/82602383-a14d7e00-9bce-11ea-8b1c-ae505f4d506f.png)</kbd>

### Dashboard Screen (Web)

<kbd>![Heat Map](https://user-images.githubusercontent.com/42619922/82602419-ae6a6d00-9bce-11ea-9aee-8a6dc16c40d5.png)</kbd>

### Metrics Screen (Web)

<kbd>![Metrics](https://user-images.githubusercontent.com/42619922/82602445-bb875c00-9bce-11ea-92a1-ff5b38f7ea22.png)</kbd>

### Patient/Incident List Screen (Web)

<kbd>![Patient List](https://user-images.githubusercontent.com/42619922/82602478-ca6e0e80-9bce-11ea-8f73-dced9ca58140.png)</kbd>

### Events Screen (Web)

<kbd>![Event List](https://user-images.githubusercontent.com/42619922/82602516-d528a380-9bce-11ea-879d-5e530de8505a.png)</kbd>

### Create Event Screen (Web)

<kbd>![Event List – Create New](https://user-images.githubusercontent.com/42619922/82602557-e70a4680-9bce-11ea-9ba6-b545c56981a7.png)</kbd>

</details>

## Milestone 1

- [ ] Setting up the new project and initial configurations. (Mobile App)

- [ ] Designing the database structure.

- [ ] Creating the database and the server using Flask.

- [ ] Setting up end-points to be consumed by the mobile application.

- [ ] Incident reporting and viewing feature. (Mobile App)

- [ ] User registration and authentication. (Mobile App)

- [ ] User profile viewing and editing feature. (Mobile App)

- [ ] Implementing events feature - front-end (Mobile App)

- [ ] Setting up the new project and initial configurations. (Web App)

- [ ] Testing for milestone 1.

- [ ] Documentation for milestone 1.

## Milestone 2

- [ ] Code refactor after milestone 1.

- [ ] Dashboard Component (Web App)
  - [ ] Heatmap.
  - [ ] Incident receiving feature.
  - [ ] Incident verification feature.
  - [ ] Incident summary feature.

- [ ] Patient/Incident List Component (Web App)
  - [ ] Incident view feature.
  - [ ] Incident searching feature.
  - [ ] Incident filtering/sorting feature.

- [ ] Metrics Component (Web App)
  - [ ] Chart visualization.
  - [ ] Metrics logic.

- [ ] Testing for milestone 2.

- [ ] Documentation for milestone 2.

## Milestone 3

- [ ] Code refactor after milestone 2.

- [ ] User registration and authentication. (Web App)

- [ ] Alerts/Events sending feature. (Web App)

- [ ] Implementing events feature - back-end (Mobile App)

- [ ] Testing for milestone 3.

- [ ] Documentation for milestone 3.

- [ ] Finalizing the project.

**Comment by ivantha** [comment]
Let's remove the extra line between each sub-milestone item 🙂 
Can you add the mockup UIs that you designed too, please?

**Comment by DonOmalVindula** [comment]
> Let's remove the extra line between each sub-milestone item 🙂
> Can you add the mockup UIs that you designed too, please?

I removed the extra lines.
The mockups are already in the issue itself. You can see them by clicking the dropdown "Proposed UI Mockups" at the very top of the description. :)
